[pytest]
addopts = -v -n auto --maxfail=2 --html=reports/report.html --self-contained-html
testpaths = tests

markers =
    smoke: smoke tests
    regression: regression tests
    regression: regression tests

